### PR TITLE
Fix error messages for private properties

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | N/A
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR         | No
| Any Dependency Changes?  | No
| License                  | MIT

These were changed when implementing the lexical topic parsing.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
@js-choi For your review. This one is smaller.

**Comment by js-choi** [comment]
Thanks. Were these test cases previously modified by #1, or did #1 accidentally make these test cases fail where they had been passing?

**Comment by js-choi** [comment]
Looks the like the answer is both. I wonder how I missed this; https://github.com/valtech-nyc/babel/pull/1/files#diff-8a085ee7dd168acc87717463e6269953 and below were changed by #1, but it looks like the message was wrong…?

**Comment by mAAdhaTTah** [comment]
My assumption was that these tests were introduced later on master and weren't present while you were developing, but who knows.

**Comment by js-choi** [comment]
Looks good to me.

**Pull request merged**
